openapi: 3.0.3
info:
  title: New Reddit API
  description: This API includes commands for interaction
  version: 1.0.0
servers:
  - url: 'https://127.0.0.1/project-backend/index.php'
paths:
  /categories:
    get:
      description: returns a list of categories
      responses:
        '200':
          description: Successfully returned a list of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    name:
                      type: string
                    description:
                      type: string
    post:
      description: Allows to create a new category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - category
                - description
              properties:
                category:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: Successfully created a new category
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
                  description:
                    type: string
  /tags:
    get:
      description: returns a list of tags
      responses:
        '200':
          description: Successfully returned a list of tags
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    name:
                      type: string
    post:
      description: Allows to create a new tag
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                tags:
                  type: array
                  items:
                    type: string
      responses:
        '201':
          description: Successfully created a new tag
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    name:
                      type: string
  /users/{id}:
    get:
      description: returns information about an user by id
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successfully returned user data
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  surname:
                    type: string
                  nickname:
                    type: string
    post:
      description: Allows to add missing information about user
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - name
                - surname
                - nickname
              properties:
                id:
                  type: string
                name:
                  type: string
                surname:
                  type: string
                nickname:
                  type: string
      responses:
        '201':
          description: Successfully added missing information about user
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  name:
                    type: string
  /posts:
    get:
      description: returns a list of posts
      parameters:
        - name: rowCount
          in: query
          description: Amount of records in a request
          schema:
            type: integer
        - name: offset
          in: query
          description: page offset
          schema:
            type: integer
      responses:
        '200':
          description: Successfully returned a list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: number
                    content:
                      type: string
                    creationDate:
                      type: string
                    updateDate:
                      type: string
                    title:
                      type: string
                    categoryId:
                      type: number
                    userId:
                      type: string
                    tagIds:
                      type: array
                      items:
                        type: number
    post:
      description: Allows to create a new post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - content
                - title
                - categoryId
                - userId
                - tagIds
              properties:
                content:
                  type: string
                title:
                  type: string
                categoryId:
                  type: number
                userId:
                  type: string
                tagIds:
                  type: array
                  items:
                    type: number
      responses:
        '201':
          description: Successfully created a new post
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  content:
                    type: string
                  creationDate:
                    type: string
                  updateDate:
                    type: string
                  title:
                    type: string
                  categoryId:
                    type: number
                  userId:
                    type: string
                  tagIds:
                    type: array
                    items:
                      type: number
  /posts/count:
    get:
      description: returns a count of all posts
      responses:
        '200':
          description: Successfully returned a count of all posts
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
  /posts/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
    get:
      description: returns a post by id
      responses:
        '200':
          description: Successfully returned a post
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  content:
                    type: string
                  creationDate:
                    type: string
                  updateDate:
                    type: string
                  title:
                    type: string
                  categoryId:
                    type: number
                  userId:
                    type: string
                  tagIds:
                    type: array
                    items:
                      type: number
    put:
      description: Allows to update a post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
                - categoryId
                - tagIds
                - userId
              properties:
                title:
                  type: string
                content:
                  type: string
                categoryId:
                  type: number
                tagIds:
                  type: array
                  items:
                    type: number
                userId:
                  type: string
      responses:
        '200':
          description: Successfully updated post title or/and content
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: number
                  title:
                    type: string
                  content:
                    type: string
                  creationDate:
                    type: string
                  updateDate:
                    type: string
                  categoryId:
                    type: number
                  userId:
                    type: string
                  tagIds:
                    type: array
                    items:
                      type: number
    delete:
      description: Allows to delete a post
      responses:
        '200':
          description: Successfully deleted post
          content:
            application/json:
              schema:
                type: string
  /comments:
    get:
      description: returns a list of comments related to the post
      parameters:
        - name: postId
          in: query
          description: id of the post
          schema:
            type: integer
      responses:
        '200':
          description: Successfully returned a list of comments
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CommentResponse"
    post:
      description: Allows to create a new comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - postId
                - content
                - userId
              properties:
                content:
                  type: string
                postId:
                  type: number
                userId:
                  type: string
                parentId:
                  type: number
      responses:
        '201':
          description: Successfully created a new comment
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CommentResponse"
  /comments/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: number
    patch:
      description: Allows to update a comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              anyOf:
                - required:
                    - userId
                    - content
                  properties:
                    content:
                      type: string
                    userId:
                      type: string
                - required:
                    - likedByUserId
                  properties:
                    likedByUserId:
                      type: string
                - required:
                    - dislikedByUserId
                  properties:
                    dislikedByUserId:
                      type: string
      responses:
        '201':
          description: Successfully updated comment
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CommentResponse"
    delete:
      description: Allows to delete a comment
      responses:
        '200':
          description: Successfully deleted comment
          content:
            application/json:
              schema:
                type: string
  /comments/count:
    get:
      description: returns a count of all comments related to the post
      responses:
        '200':
          description: Successfully returned a count of all comments related to the post
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number

components:
  schemas:
    CommentResponse:
      type: object
      properties:
        id:
          type: number
        title:
          type: string
        content:
          type: string
        creationDate:
          type: string
        updateDate:
          type: string
        categoryId:
          type: number
        userId:
          type: string
        tagIds:
          type: array
          items:
            type: number